#!/usr/bin/perl -w

=head1	NAME

oo2pod - PerlPoint generation from an OpenOffice.org document

=head1	SYNOPSIS

Usage : oo2pp <oofilename>

=head1	DESCRIPTION

=cut

# pragma
use strict;

# load modules
use Carp;
use OpenOffice::PerlPoint;

# build a converter object
my $oo2pp=new OpenOffice::PerlPoint(
                                    file => $ARGV[0],
                                   );

# convert document
print $oo2pp->oo2pp;
